### PR TITLE
refine options for tcpping

### PR DESCRIPTION
**Pull request by pizhenwei**
This PR includes 3 patches:
1, Add '-P srcport' in usage
2, Add '-h' option for usage
3, Sort options as alphabet order

### CODE REVIEW

**Comment by pacepi** [comment]
@jwyllie83 PING

**Comment by jwyllie83** [comment]
Thanks for the pull request; the logic looks good to me.  I think there's a bug in the -t option (that was present previously, too), however: it will allow setting an invalid TTL and continuing execution.  If you're in the code, would you mind doing something better with that (exiting, setting a default, something else) and amending the pull request?  If not, I can do it too, but I figured I'd let you know as you have the code open already.

Thanks so much!

**Comment by pacepi** [comment]
@jwyllie83 
Hey, JIm,
I pushed a new commit -- 'Exit program when invalid TTL option'  as you suggested.

**Comment by pacepi** [comment]
@jwyllie83 PING

**Comment by pacepi** [comment]
@jwyllie83 PING

**Comment by pizhenwei** [comment]
@jwyllie83 PING

**Comment by jwyllie83** [comment]
ACK -- sorry about mising this.  I'll have a look now.

**Comment by jwyllie83** [comment]
Looks good to me -- merged.  Thanks!

**Pull request merged**
